version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
    # Depending on how the backend docker is set up, you might want to attach this to a shared network
    # networks:
    #   - af-crm-network
